# Generated by Django 2.1.2 on 2018-10-26 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('intro_header', models.CharField(max_length=50)),
                ('intro_text', models.TextField()),
                ('dashboard_embed', models.TextField()),
                ('dashboard_aspect_ratio_width', models.PositiveSmallIntegerField(default=16)),
                ('dashboard_aspect_ratio_height', models.PositiveSmallIntegerField(default=9)),
                ('pop_stat', models.CharField(max_length=5)),
                ('pop_stat_label', models.CharField(max_length=10)),
                ('pop_stat_explainer', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.Category')),
            ],
        ),
    ]
