# Generated by Django 2.1.2 on 2018-11-29 15:22

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Indicator name. I.E. Early Indicators of Future Success.', max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.Category')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Reference for internal use only. Does not display.', max_length=20)),
                ('question', models.CharField(help_text='I.E. What career education programs are available to students?', max_length=200)),
                ('text', tinymce.models.HTMLField(help_text='Explanatory text.')),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('dashboard_embed', models.TextField(help_text='Embed code from PowerBI')),
                ('aspect_ratio_width', models.PositiveSmallIntegerField(default=16, help_text='Defaults to 16x9')),
                ('aspect_ratio_height', models.PositiveSmallIntegerField(default=9, help_text='Defaults to 16x9')),
                ('pop_stat', models.CharField(help_text='Number that displays in the pop-stat at the top of the screen. Include %$ etc. 5 character max', max_length=5)),
                ('pop_stat_label', models.CharField(help_text='Label at the top of the pop-stat. 12 character max.', max_length=12)),
                ('pop_stat_explainer', models.CharField(help_text='Explainer under the pop-stat. 60 character max.', max_length=60)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.Indicator')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
