# Generated by Django 2.1.2 on 2018-10-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='dashboard_aspect_ratio_height',
            new_name='aspect_ratio_height',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='dashboard_aspect_ratio_width',
            new_name='aspect_ratio_width',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='intro_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='intro_header',
        ),
        migrations.AddField(
            model_name='indicator',
            name='header',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicator',
            name='question',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
