# Generated by Django 2.1.2 on 2018-10-29 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20181029_1322'),
        ('indicators', '0002_auto_20181026_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Reference for internal use only. Does not display.', max_length=20)),
                ('header', models.CharField(help_text='I.E. Career Education', max_length=200)),
                ('question', models.CharField(help_text='I.E. What career education programs are available to students?', max_length=200)),
                ('text', models.TextField(help_text='Explanatory text. Need to wrap paragraphs in P tags')),
                ('dashboard_embed', models.TextField(help_text='Embed code from PowerBI')),
                ('aspect_ratio_width', models.PositiveSmallIntegerField(default=16, help_text='Defaults to 16x9')),
                ('aspect_ratio_height', models.PositiveSmallIntegerField(default=9, help_text='Defaults to 16x9')),
                ('pop_stat', models.CharField(help_text='Number that displays in the pop-stat at the top of the screen. Include %$ etc. 5 character max', max_length=5)),
                ('pop_stat_label', models.CharField(help_text='Label at the top of the pop-stat. 10 character max.', max_length=10)),
                ('pop_stat_explainer', models.CharField(help_text='Explainer under the pop-stat.', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='category',
        ),
        migrations.DeleteModel(
            name='Indicator',
        ),
    ]
