# Generated by Django 2.1.2 on 2018-11-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='indicator',
        ),
        migrations.DeleteModel(
            name='Indicator',
        ),
    ]
