# Generated by Django 2.1.2 on 2018-11-29 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_auto_20181129_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
