# Generated by Django 2.1.2 on 2018-10-29 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_auto_20181029_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='indicator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='indicators.Indicator'),
            preserve_default=False,
        ),
    ]
