# Generated by Django 2.1.2 on 2019-01-15 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_agency_url'),
        ('indicators', '0004_auto_20181129_1358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Indicator',
        ),
    ]
