# Generated by Django 2.1.2 on 2018-10-30 15:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_auto_20181029_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=tinymce.models.HTMLField(help_text='Explanatory text.'),
        ),
    ]
