# Generated by Django 2.1.2 on 2018-10-31 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_auto_20181030_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['pk']},
        ),
    ]
