# Generated by Django 2.1.2 on 2018-10-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_auto_20181031_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pop_stat_explainer',
            field=models.CharField(help_text='Explainer under the pop-stat. 60 character max.', max_length=60),
        ),
        migrations.AlterField(
            model_name='question',
            name='pop_stat_label',
            field=models.CharField(help_text='Label at the top of the pop-stat. 12 character max.', max_length=12),
        ),
    ]
