# Generated by Django 2.1.2 on 2018-11-29 15:09

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, help_text='auto fill if it is blank', null=True, unique=True)),
                ('navigation_name', models.CharField(max_length=20)),
                ('category_page_image', models.ImageField(upload_to='category_headers')),
                ('category_page_image_offset', models.IntegerField(default=50, help_text='Percent from top to offset the header image.')),
                ('intro_header', models.CharField(max_length=200)),
                ('intro_text', tinymce.models.HTMLField()),
                ('at_a_glance_label', models.CharField(help_text='Rhode Island ??? at a glance', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
