# Generated by Django 2.1.2 on 2018-10-30 15:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20181029_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='at_a_glance_label',
            field=models.CharField(default='K-12', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='intro_text',
            field=tinymce.models.HTMLField(),
        ),
    ]
