# Generated by Django 2.1.2 on 2019-01-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20181129_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='agency_url',
            field=models.URLField(blank=True, help_text='Agency URL', max_length=100, null=True),
        ),
    ]
