# Generated by Django 2.1.2 on 2018-10-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20181031_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_page_image_offset',
            field=models.IntegerField(default=50, help_text='Percent from top to offset the header image.'),
        ),
    ]
